#!/bin/sh


echo "Setting up Terminal Velocity lab ..."

yum install -y https://rpmfind.net/linux/epel/8/Everything/x86_64/Packages/c/cowsay-3.04-16.el8.noarch.rpm

yum install -y https://rpmfind.net/linux/dag/redhat/el3/en/x86_64/dag/RPMS/fortune-1.0-37.1.el3.rf.x86_64.rpm

useradd -m pi

passwd pi
raspberry
raspberry

usermod -aG wheel pi

su - pi

mkdir /home/pi/Pictures
mkdir /home/pi/python_games
mkdir '/home/pi/Scratch Projects'
mkdir /home/pi/Videos
mkdir /home/pi/Documents
mkdir /home/pi/Music
mkdir /home/pi/Public
mkdir /home/pi/Scratch
mkdir /home/pi/Templates

echo "Set up and ready"
